### ISSUE TITLE
Shuffle and repeat controls not visible

### ISSUE THREAD

**Issue by dubbub801** [nikclayton/android-squeezer#676]
Shuffle and repeat controls are not visible. 

The controls are there and function if you know where to tap. Issue exist in either normal or dark modes.
![Screenshot_20210216-080804](https://user-images.githubusercontent.com/79155888/108085609-beff2500-7032-11eb-93e1-a01e4de4383c.png)

Version 2.2.2
Android 9

**Comment by kaaholst** [comment]
Hmm... I just tested with a Android 9 device, and the buttons are visible. 

To help pinpoint this issue please answer a few questions:

1. I have just released as version 2.2.3 of Squeezer, which in order to restore the scroll bar contains an update of the material design design library, which we use to for these buttons. Does that fix this issue?
2. Please give details about the device running Squeezer, i.e. Android version, Brand and model.

Thank you!

**Comment by dubbub801** [comment]
Problem persists with version 2.2.3.

LG G7 ThinQ
Model: LM-G710ULM
Rev: 1.0

Android 9
Kernel: 4.9.112
Build: PKQ1.181105.001
Software Version: G710ULM20f
